
site_name: Subnautica Data Framework
site_url: https://docs.sn2-sdf.dev/
site_description: This site has all documentation necessary to create content mods using SDF

theme:
  name: material
  palette:
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode

    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to system preference

repo_url: https://github.com/LimoDerEchte/SDF-Docs/

nav:
  - Home: index.md
  - Getting Started:
      - Installation: setup/installation.md
      - Project Structure: setup/project.md
  - Data Assets:
      - Crafting Recipes: data/recipes.md
      - Crafting Recipe Categories: data/recipe_categories.md
  - Generic Formats:
      - Icon Notation: generic/icons.md